# No Copyright (-) 2010 The Ampify Authors. This file is under the
# Public Domain license that can be found in the root LICENSE file.

include $(GOROOT)/src/Make.$(GOARCH)

TARG=amplzf
# TARG=amp/lzf
GOFILES=\
        lzf.go\

include $(GOROOT)/src/Make.cmd
# include $(GOROOT)/src/Make.pkg
