# No Copyright (-) 2010 The Ampify Authors. This file is under the
# Public Domain license that can be found in the root LICENSE file.

include $(GOROOT)/src/Make.inc

TARG=amp/big
GOFILES=\
	arith.go\
	arith_decl.go\
	int.go\
	nat.go\
	rat.go\

OFILES=\
	arith_$(GOARCH).$O\

include $(GOROOT)/src/Make.pkg
