# Public Domain (-) 2010-2011 The Ampify Authors.
# See the Ampify UNLICENSE file for details.

include $(GOROOT)/src/Make.inc

TARG=amp
GOFILES=\
	amp.go\
	frontend.go\
	init.go\
	master.go\
	node.go\
	run.go\

include $(GOROOT)/src/Make.cmd
