#! /usr/bin/env python
# -*- coding: utf-8 -*-

# No Copyright (-) 2008-2010 The Ampify Authors. This file is under the
# Public Domain license that can be found in the root LICENSE file.

"""
=======
Tentapp
=======

A micro-data powered collaboration platform.

"""

import sys

# ------------------------------------------------------------------------------
# Main Runner
# ------------------------------------------------------------------------------

def main():

    argv = sys.argv[1:]

# ------------------------------------------------------------------------------
# Self Runner
# ------------------------------------------------------------------------------

if __name__ == '__main__':
    main()
