# Public Domain (-) 2011 The Ampify Authors.
# See the Ampify UNLICENSE file for details.

include $(GOROOT)/src/Make.inc

TARG=amp/master
GOFILES=\
        master.go\

include $(GOROOT)/src/Make.pkg
