# Public Domain (-) 2011 The Ampify Authors.
# See the Ampify UNLICENSE file for details.

include $(GOROOT)/src/Make.inc

TARG=amp/rpc
GOFILES=\
        header.go\
		rpc.go\

include $(GOROOT)/src/Make.pkg
