#! /bin/sh

# Public Domain (-) 2010-2011 The Ampify Authors.
# See the Ampify UNLICENSE file for details.

if [ "x$1" == "xignored" ]; then
	grep "^#" $0 | grep -v "bin/sh" | grep -v "Public Domain" | grep -v UNLICENSE
	exit
fi

python -c "from datetime import datetime as d, timedelta as t; \
           left = d(2011, 3, 1) - d.now(); \
           days, left = left.days, left.seconds; \
           left, seconds = divmod(left, 60); \
           hours, minutes = divmod(left, 60); \
           print '# Time left:'; \
           print '     %s days, %s hrs, %s mins, %s secs' % (days, hours, minutes, seconds)"

TODO_FILE=$0

echo
echo "# Todo:"
grep "^✗" $TODO_FILE | wc -l

echo
echo "# Done:"
grep "^✓" $TODO_FILE | wc -l

echo
echo "# Total:"
grep "^[✓✗]" $TODO_FILE | wc -l

cat >> /dev/null << EOF

=====
Admin
=====

✗ dns setup
✗ hostway servers order
✗ base linux setup on servers
✗ ssl certificates
✗ http setup including redirects from apex domains
✗ ampzero deployment

=======
Process
=======

✓ git review
✓ git review init
✓ git review: builtins
✓ git review: github cross repository compare
✓ git review: diff view
✓ git review: comment
✓ git review: test runner
✓ git review: build slave
✓ git review: try bot
✓ git review: watchlist
✓ git review: view

✓ amp test

============
Installation
============

✓ configure
✓ make

✓ amp build: init
✓ amp build: config
✓ amp build: packages
✓ amp build: distribution
✓ amp build: install
✓ amp build: uninstall
✓ amp build: build recipes

✓ package: base dependencies
✓ package: zlib
✓ package: bz2
✓ package: readline
✓ package: libnatpmp
✓ package: miniupnc
✓ package: redis
✓ package: go
✓ package: nodejs
✓ package: coffeescript
✓ package: pcre
✓ package: nginx
✓ package: openssl
✓ package: python
✓ package: cython
✓ package: sass
✓ package: python-packages
✓ package: berkeleydb
✓ package: keyspace

# package: freetype
# package: libjpeg
# package: libpng
# package: python imaging library
# package: qrencode
# package: libevent
# package: libxml2
# package: libxslt
# package: lxml
# package: git
# package: gevent

✓ assetgen
✗ update build distfiles
✗ redpill: daemon
✗ redpill: deploy
✗ redpill: pre/post deploy scripts

===========
Ampify Zero
===========

✗ ampzero: main()
✗ ampzero: command line arguments handler
✗ default configuration
✗ configuration handler

✗ modern browser: update view
✓ google analytics

✗ weblite: request
✗ weblite: response
✗ weblite: services
✗ weblite: security
✗ weblite: template

✗ design: site css
✗ design: general layout
✗ design: buttons
✗ design: sidebar
✗ design: trust maps editor
✗ design: trust maps graph
✗ design: dols
✗ design: default profile pic
✗ design: input box
✗ design: auto-completion

✗ input box
✗ input box word/char count/limit
✗ input box contenteditable
✗ input box current place finder in content area
✗ input box auto-completion
✗ input box auto-completion -- users
✗ input box auto-completion -- aspects
✗ input box auto-completion -- services
✗ input box auto-completion -- spaces
✗ input box date input, 2010-01-13T21:34Z
✗ input box time input, 21:34
✗ input box currency input
✗ input box transboolean
✗ input box map input
✗ input box links
✗ input box rich text
✗ input box ~ naming/aliasing
✗ input box "to" field

✗ autogrowing editor
✗ inline editor
✗ auto-preview + error reporter
✗ position list editor
✗ uploader

✗ google maps
✗ map view: non-https load
✗ map view: rendering
✗ map view: search (geocode) + voice search
✗ map view: design
✗ location discovery
✗ location -> datastore boxes
✗ map view: magic zoom

✗ ~ names
✗ ~ management
✗ ~ redirects

✗ calendar display
✗ calendar view
✗ calendar (streak)

✗ loading indicator
✗ load cache
✗ load on scroll
✗ scrollbars
✗ scrollbars theme

✗ dol control: search
✗ dol control: global/trusted
✗ dol control: view
✗ dol column auto-size

✗ introduction service
✗ introduction service: view

✗ messaging view
✗ messaging auto-split handler
✗ messaging first-contact view

✗ item editing view
✗ item versioning view
✗ item positioning view
✗ item deleting view
✗ edit controls
✗ edit version

✗ user profile view
✗ user "edit" (trust) view
✗ user "edit" (trust) controls

✗ space view
✗ space edit controls

✗ item display
✗ uploaded border indicator
✗ in-flight indicator and cache/load interplay

✗ /me display
✗ /topic display
✗ /topic handling
✗ /user/perspective handling
✗ /trust handling
✗ /pecu handling
✗ /intention handling
✗ /need handling
✗ list value handling
✗ questions handling
✗ question options view
✗ question answer view
✗ answers handling

✗ .commands
✗ .commands completion
✗ ? help commands
✗ service formatters
✗ service formatters: command
✗ service formatters: script
✗ media player commands

✗ +drafts
✗ +sent
✗ auto-save

✗ amp-ing
✗ re-spacing
✗ pecu-allocating
✗ commenting
✗ symlinking
✗ original chain traversal
✗ via trail

✗ item search
✗ search syntax
✗ search query parser
✗ query subset params
✗ client-side search results merge
✗ parallel query
✗ merged aspect/value query

✗ shaila mode
✗ shaila mode editor
✗ shaila mode item select
✗ shaila mode view
✗ shaila item render

✗ include parser
✗ inclusions retrieve and cache
✗ inclusions expand
✗ inclusions invalidate
✗ include failure display
✗ include aspect
✗ include specific#parts

✗ message parser
✗ message urls detect
✗ links interceptor -- malware warning

✗ fonts
✗ fonts: loader
✗ fonts: font files
✗ fonts: css

✗ embed
✗ embed: image proxy
✗ embed: image ref rewriter
✗ embed: skitch/flickr/twitpic
✗ embed: github gists
✗ embed: mp3
✗ embed: soundcloud
✗ embed: pdf/powerpoint
✗ embed: youtube/vimeo
✗ embed: videos
✗ embed: longurls support
✗ embed: store data

✗ spotify uris
✗ skype uris

✗ paste handler
✗ text upload
✗ text upload view
✗ preview view

✗ file quotas
✗ file upload
✗ file upload (in background)
✗ file upload (drag and drop)
✗ file access
✗ file management
✗ file image preview
✗ file font
✗ file mp3 player
✗ file html5 video player
✗ file download

✗ media html5 video
✗ media youtube
✗ media mp3
✗ media playlist
✗ media control
✗ media auto-pecu allocation
✗ media player: view
✗ media player: design

✗ dols management
✗ dols session
✗ dols minimise/expand
✗ dols notification
✗ dols rearrange

✗ session new
✗ session support
✗ session load link /#session-evangineer-28937/~thruflo/foo
✗ session save (with name)
✗ session restore
✗ forward/back buttons -- bookmarkability
✗ permalink

✗ error handling
✗ error message display
✗ handle code updated/reload mechanism

✗ initialise user session
✗ items cache
✗ live connection

✗ web sockets client-side support
✗ iframe client-side support
✗ postMessage client-side support

✗ cross-site comms
✗ cross-site auth
✗ cross-site tokens

✗ top-40 dampener

✗ preferred language settings
✗ google translation
✗ transliteration support

✗ undo actions: client
✗ undo actions: backend
✗ keyboard controls
✗ stylised reader mode
✗ stylised reader cache

✗ cajoleit
✗ caja host
✗ caja service loader
✗ caja service api
✗ caja service builtins
✗ caja service capabilities

✗ builtins: urlfetch/open
✗ builtins: dom fragment
✗ builtins: template
✗ builtins: call
✗ builtins: query
✗ builtins: user
✗ builtins: space
✗ builtins: link
✗ builtins: token
✗ builtins: get-lines
✗ builtins: find
✗ builtins: get
✗ builtins: save
✗ builtins: send

✗ amp script: parser
✗ amp script: pipeline
✗ amp script: variables
✗ amp script: runner
✗ amp script: context

✗ js yaml parser
✗ js yaml metadata extraction

✗ timezone settings
✗ js timezone support
✗ olson db -> js data
✗ relative time display
✗ ical output
✗ shared event time setting/planning
✗ countdown -- it's on at!

✗ events app
✗ events app: view
✗ events app: event creator
✗ events app: event editor

✗ trust maps management
✗ trust maps view
✗ trust maps graph view

✗ amp creds settings view
✗ amp creds needed view
✗ amp creds transfer view (handle negtive/zero)

✗ client-side caches

✗ iphone/ipad css
✗ iphone/ipad js
✗ iphone/ipad dynamic column view
✗ iphone/ipad input
✗ iphone/ipad touch events

✗ code editor
✗ code editor: preview
✗ code editor: handler
✗ code editor: syntax highlighter
✗ code editor: live output renderer
✗ code editor: error reporter

✗ mail service
✗ mail service: smtp client
✗ mail service: sendgrid support
✗ mail service: incoming handler

✗ urlfetch service
✗ urlfetch service: caller
✗ urlfetch service: headers
✗ iana-reserved ips
✗ ssl cert verification

✗ images service
✗ images service: resize/rotate
✗ images service: nodule
✗ images service: caller
✗ images service: functions

✗ taskqueue service
✗ taskqueue service: caller
✗ taskqueue service: functions

✗ memstore service
✗ memstore service: caller
✗ memstore service: functions

✗ routing service
✗ routing service: caller
✗ routing service: functions

✗ peerfund service
✗ peerfund service: caller
✗ peerfund service: functions
✗ peerfund service: templates
✗ peerfund service: accounts

✗ confluence app
✗ confluence app: view
✗ confluence app: timeline
✗ confluence app: graph view

✗ http -> https redirect
✗ upgrade notifier: html page, json

✗ global trust map config
✗ global trust map query
✗ global trust map proxy
✗ global trust map calculation

✗ trust metrics calculation
✗ trust metrics cache
✗ trust metrics loader
✗ incomplete trust maps calculation/results notifier
✗ anti top-40 inertia measures

✗ file server
✗ file transfer: tit-for-tat
✗ file transfer: tree hash
✗ file transfer: combined hasher support
✗ file transfer: multi-transfer
✗ file transfer: range get
✗ file transfer: upload
✗ file transfer: video progressive/stream

✗ frontend
✗ frontend proxy
✗ frontend upgrade
✗ http server
✗ xsrf tokens

✗ request handling
✗ http request parser
✗ https request handler

✗ openvpn setup
✗ openvpn multihome updater script

✗ tls support
✗ tls connection
✗ tls server init

✗ dmca support
✗ dmca service

✗ query data handling
✗ post data handling
✗ argonought data handling

✗ template renderer
✗ template escaper
✗ production/debug modes
✗ static file serving/invalidation
✗ static function

✗ nodule dispatcher
✗ nodule dispatcher: call
✗ nodule dispatcher: remote node

✗ www request
✗ ampsite request
✗ ampsite / ampclient files
✗ item request
✗ ~user request
✗ space request

✗ www template
✗ www view
✗ ampsite template
✗ ampsite view

✗ registration view
✗ registration handler
✗ login handler
✗ login view
✗ logout handler
✗ logout view

✗ redirect handler
✗ http cache: etags, last-modified, if-modified-since
✗ proxy caching
✗ unauth handler

✗ argonought encoding
✗ argonought calls: synchronous
✗ argonought calls: async
✗ argonought encodes of special typed values

✗ current sensors check
✗ current sensors view
✗ current sensors refresh

✗ identity service
✗ identity service: caller

✗ user model
✗ user registration
✗ user authentication
✗ user authorisation
✗ user quotas
✗ user profile
✗ user profile picture
✗ user settings
✗ user trust maps
✗ user follows
✗ user amp creds account
✗ user subscriptions
✗ user pecu account
✗ user access tokens

✗ default profile picture
✗ profile pic update

✗ user invitation
✗ user mail-out / email list / confirmation mail reply
✗ user payments model
✗ user payments

✗ paypal: basic api + simple pay link
✗ paypal: recurring payments
✗ paypal: adaptive payments
✗ paypal: buy amp creds
✗ paypal: pecu payouts

✗ default spaces
✗ default tokens

✗ datastore service
✗ datastore service: caller
✗ datastore service: serialisation
✗ datastore service: disk store
✗ datastore service: memstore
✗ datastore service: incremental encoding
✗ datastore service: scan
✗ datastore service: index generation
✗ datastore service: index update
✗ datastore service: rollback
✗ datastore service: index rollback
✗ datastore service: api
✗ datastore service: put
✗ datastore service: get
✗ datastore service: query
✗ datastore service: query / zig zag
✗ datastore service: query / parallel
✗ datastore service: query / planner
✗ datastore service: replicate
✗ datastore service: keyspace
✗ datastore service: paxos
✗ datastore service: lease
✗ datastore service: log
✗ datastore service: transaction
✗ datastore service: transaction keyspace handler
✗ datastore service: transaction run
✗ datastore service: transaction commit
✗ datastore service: transaction rollback
✗ datastore service: blobstore
✗ datastore service: sensor integration

✗ item model
✗ item multi model
✗ item creation
✗ item updating
✗ item versioning
✗ item positioning
✗ item deleting

✗ space validation
✗ amp-ing validation

✗ updated aspect handling

✗ parser
✗ unicode handling
✗ attachment/file handling
✗ link parsing
✗ aspect parsing
✗ #! handler parsing
✗ versioned parser live upgrading

✗ language detection
✗ language models generation
✗ language models -> json

✓ javascript ucd -- part 1
✗ javascript ucd -- part 2
✗ javascript unicode normalisation
✗ javascript case-folding normalisation
✗ go ucd -- part 1
✗ go ucd -- part 2
✗ go unicode normalisation
✗ go case-folding normalisation
✗ link normalisation

✗ search query parser
✗ query subset params
✗ /aspect search

✗ boolean encoding/search
✗ to encoding/search
✗ about encoding/search
✗ refs encoding/search
✗ links encoding/search
✗ includes encoding/search
✗ list encoding/search
✗ numbers encoding/search
✗ phrase encoding/search
✗ geo-location encoding/search
✗ date encoding/search
✗ time/timedelta encoding/search
✗ amp creds encoding/search
✗ currency encoding/search
✗ language encoding/search
✗ units encoding/search
✗ pecus encoding/search
✗ multi encoding/search

✗ argonought: boolean
✗ argonought: string
✗ argonought: quasi
✓ argonought: number
✓ argonought: integer
✗ argonought: date
✗ argonought: time
✗ argonought: datetime
✗ argonought: timedelta
✗ argonought: currency
✗ argonought: units
✗ argonought: geo-location
✗ argonought: pecus
✗ argonought: language
✗ argonought: amp
✗ argonought: list
✗ argonought: link
✗ argonought: user
✗ argonought: aspect
✗ argonought: spaces
✗ argonought: tokens

✗ transaction lock / lease
✗ transaction save
✗ pecu totals

✗ double entry support
✗ amp creds: service
✗ amp creds: caller
✗ amp creds: account model
✗ amp creds: transfer
✗ amp creds: transaction
✗ amp creds: transaction fee

✗ hashcash generator
✗ hashcash verifier

✗ user messaging

✗ controlled spaces
✗ controlled space creation view
✗ controlled space invitation view

✗ access tokens management
✗ access tokens model
✗ access tokens creation
✗ access tokens revoke
✗ access tokens share

✗ trust maps
✗ trust maps listing
✗ trust maps query

✗ json encoding
✗ json decoding

✗ parallel query
✗ parallel query cursor
✗ parallel query filter
✗ parallel query memcache
✗ parallel query sensor notify

✗ sanitiser
✗ sanitiser: dom elements
✗ sanitiser: jsonp
✗ sanitiser: css
✗ sanitiser: xss check
✗ sanitiser: cache

✗ markdown convert
✗ markdown syntax highlight for code
✗ markdown github changes
✗ markdown with {{inclusions}}
✗ markdown + sanitiser
✗ markdown preview view
✗ syntax highlighter for code

✗ render: raw
✗ render: code
✗ render: html
✗ render: text
✗ render: js
✗ render: coffee
✗ render: template

✗ math rendering support
✗ [[links]]

✗ trends model
✗ trends updating
✗ trends calculation
✗ trends query
✗ trends service
✗ trends view
✗ trends search
✗ trends listing

✗ auto-completion query support
✗ auto-completion cache support

✗ oauth support
✗ oauth server
✗ oauth client
✗ oauth settings
✗ oauth clients view

✗ redis configuration
✗ redis nodule
✗ redis manager
✗ redis client library

✗ redis-keyspace partitioner
✗ redis-keyspace detector
✗ redis-keyspace initialiser
✗ redis-keyspace routing
✗ redis-keyspace lease management

✗ live node
✗ live node daemon
✗ live node manager
✗ live node configuration
✗ live node index file
✗ live node ping file
✗ live node base javascript

✗ real-time update
✗ web sockets support

✗ request authentication
✗ datastore-verified authentication

✗ sensor service
✗ sensor service: caller
✗ sensor network
✗ sensor pattern match finder
✗ send code updated signal
✗ resync checker

✗ node connection stats
✗ worker nodule
✗ web hooks confirmation handler
✗ web hooks post handler
✗ memcache invalidation handler

✗ github integration

✗ google calendar integration: in
✗ google calendar integration: out

✗ twitter: oauth
✗ twitter: link to user account
✗ twitter: settings view
✗ twitter: "post to" support
✗ twitter: post
✗ twitter: connected friends

✗ facebook: oauth
✗ facebook: link to user account
✗ facebook: settings view
✗ facebook: "post to" support
✗ facebook: post
✗ facebook: connected friends

✗ anonymous posting
✗ anonymous posting: payment

✗ register sensor callback handler
✗ port phenny services

✗ log to datastore handler
✗ log to disk handler

✗ logging service
✗ logging service: caller

✗ request logging
✗ error logging
✗ error logging: micro-format (user, a/b tests)
✗ service request logging
✗ service error logging
✗ live request logging
✗ live error logging
✗ input external data, e.g. user plans, quotas, etc.

✗ quota tracking
✗ quota limits
✗ quota limit setter
✗ quota usage logger
✗ quota usage view

✗ async s3 client
✗ logs saver to s3
✗ logs saver to redis
✗ datastore saver to s3
✗ datastore restore from s3

✗ log store view
✗ log store configuration
✗ log model

✗ remonit data input sources
✗ remonit configuration
✗ remonit notification
✗ public status app
✗ public status app charts

✗ espian democracy
✗ espian democracy: who is eligible
✗ espian democracy: space
✗ espian democracy: context jury
✗ espian democracy: access
✗ espian democracy: propose
✗ espian democracy: deliberate
✗ espian democracy: recommend
✗ espian democracy: vote

✓ optparse
✓ command-line auto completion
✓ yaml parser nodule
✓ yaml parser caller
✓ lzf compression

✗ badges
✗ buy badges
✗ assign badges
✗ tasks for badges
✗ handshake protocol

✗ letterbox protocol
✗ charts
✗ base32
✗ predictions
✗ dynamic favicon updater

======
Future
======

# amphub deployment
# amp deployment
# ampnode binary upgrade
# blacklist ip/networks

# amp config handling
# amp init
# amp hub registration: host
# amp hub registration: user
# amp sign: new node
# amp run
# amp run --no-hub
# amp run --server
# amp run --services

# detect node on local subnet from teredo IP
# rendezvous support
# rendezvous announce

# local names support
# on-save name->id mapping
# on-load id->name mapping

# pie menu
# pie menu: design
# pie menu: options hook

# mapreduce handlers
# mapreduce generated results view

# mappers
# reducers
# default jobs, e.g. top users
# a/b test jobs
# reports interface
# report charts

# usage tips
# virtual users, e.g. britney-spears, appa, etc.

# pair encoding/search
# argonought: pair
# argonought: float
# argonought: complex
# argonought: set
# argonought: dict
# argonought: named value
# argonought: call
# argonought: element
# argonought: ip
# argonought: range
# argonought: code
# argonought: object

# fonts: naaga
# code editor: naaga syntax
# mail service: naaga support
# urlfetch service: naaga
# images service: naaga
# taskqueue service: naaga
# memstore service: naaga
# routing service: naaga
# peerfund service: naaga
# identity service: naaga
# datastore service: naaga
# amp creds: naaga
# sensor service: naaga
# logging service: naaga
# web services service: naaga

# naaga
# naaga: tokeniser
# naaga: lexer
# naaga: parser
# naaga: parser combinator
# naaga: quasi literals
# naaga: auto-sanitising html
# naaga: templated expansion
# naaga: element literals
# naaga: auto-binding
# naaga: coherent reaction
# naaga: tick
# naaga: reaction ordering
# naaga: auto-value propagation
# naaga: lexical scoping
# naaga: auto-scope binding
# naaga: """strings"""
# naaga: comments
# naaga: package
# naaga: service call
# naaga: versioning
# naaga: help/preview
# naaga: dom sandboxing
# naaga: dom query
# naaga: do blocks
# naaga: if/else conditionals
# naaga: comparisons
# naaga: pipe operator
# naaga: for loops
# naaga: while loops
# naaga: list comprehensions
# naaga: set comprehensions
# naaga: dict comprehensions
# naaga: functions
# naaga: function calls
# naaga: blocks
# naaga: try/catch
# naaga: try/catch/finally
# naaga: lazy ranges
# naaga: slices
# naaga: eval
# naaga: assignment
# naaga: variables
# naaga: multiple assignment
# naaga: assignment swap
# naaga: repl
# naaga: order precendence
# naaga: exponentiation
# naaga: square roots
# naaga: ? operator
# naaga: % remainder operator
# naaga: and/or operators
# naaga: sub expresions
# naaga: mixed list/dict object
# naaga: make object
# naaga: i18n
# naaga: timezones
# naaga: raphael graphs
# naaga: html generation

# amptp
# amptp what is my ip
# amptp upnp/natpmp
# amptp upnp/natpmp nodule
# amptp udp bind
# amptp ordering
# amptp ordering 2
# amptp framing
# amptp framing 2
# amptp framing 3

# amptp congestion control
# amptp congestion control 2
# amptp congestion control 3
# amptp secure connection
# amptp secure connection 2
# amptp secure connection 3
# amptp recall connection
# amptp ping
# amptp auto-compression

# naaga argo: string
# naaga object: string
# naaga argo: quasi
# naaga object: quasi
# naaga argo: number
# naaga object: number
# naaga argo: integer
# naaga object: integer
# naaga argo: float
# naaga object: float
# naaga argo: complex
# naaga object: complex
# naaga argo: date
# naaga object: date
# naaga argo: time
# naaga object: time
# naaga argo: datetime
# naaga object: datetime
# naaga argo: timedelta
# naaga object: timedelta
# naaga argo: currency
# naaga object: currency
# naaga argo: units
# naaga object: units
# naaga argo: pair
# naaga object: pair
# naaga argo: geo-location
# naaga object: geo-location
# naaga argo: pecus
# naaga object: pecus
# naaga argo: language
# naaga object: language
# naaga argo: amp
# naaga object: amp
# naaga argo: list
# naaga object: list
# naaga argo: set
# naaga object: set
# naaga argo: dict
# naaga object: dict
# naaga argo: named value
# naaga object: named value
# naaga argo: link
# naaga object: link
# naaga argo: user
# naaga object: user
# naaga argo: aspect
# naaga object: aspect
# naaga argo: call
# naaga object: call
# naaga argo: element
# naaga object: element
# naaga argo: ip
# naaga object: ip
# naaga argo: range
# naaga object: range
# naaga argo: code
# naaga object: code
# naaga argo: object
# naaga object: object
# naaga argo: spaces
# naaga object: spaces
# naaga argo: tokens
# naaga object: tokens

# rss feed service
# rss feed service: caller
# rss feed service: parser
# rss feed service: naaga handler
# rss feed service: cache
# rss feed generator for __format__=rss

# offline: mode switcher
# offline: cache
# offline: consumption view

# relay service
# relay service: caller
# relay service: naaga
# relay service: functions
# relay service: setup
# relay service: request
# relay service: accept
# relay service: update

# amphub service
# amphub service: caller
# amphub service: naaga
# amphub service: functions
# amphub service: registration
# amphub service: update

# ampauth server
# ampauth client
# ampauth views

# cert generate
# cert sign
# cert loading

# naaga service
# naaga service: nodejs nodule
# naaga service: multi process
# naaga service: base runtime
# naaga service: error handler
# naaga service: package
# naaga service: loader
# naaga service: callback
# naaga service: auth
# naaga service: call services
# naaga service: timeout

# naaga: package
# naaga: versioning support
# naaga: remote call

# code editor: wysiwyg field
# code editor: scroll
# code editor: cut/paste
# code editor: text
# code editor: autocompletion
# code editor: help viewer
# code editor: commands

# lzf compression: dictionary-support
# amptp request parser
# upgrade notifier: amptp

# service tokens
# service tokens: transfer
# service tokens: storage
# service tokens: processing
# service tokens: request

# js transaction handling
# pecu allocations
# pecu totals

# ipv4 support
# ipv6 support

# web services service
# google map geocoding call

# magic db
# magic detector -> mimetype
# geoip data
# geoip parser/lookup

# remonit web interface
# remonit status interface
# remonit recent logs interface
# remonit error reporting interface
# public status app access verification

# amp creds exchange
# replication update amphub
# github key generation
# recurring events

# replication service
# replication request
# replication accept
# replication pattern handler
# replication notification

EOF
