# Public Domain (-) 2010-2011 The Ampify Authors.
# See the Ampify UNLICENSE file for details.

include $(GOROOT)/src/Make.inc

TARG=webserver
GOFILES=\
	webserver.go\

include $(GOROOT)/src/Make.cmd
