#! /usr/bin/env python

# No Copyright (-) 2010 The Ampify Authors. This file is under the
# Public Domain license that can be found in the root LICENSE file.

import sys

from os.path import abspath, dirname, isfile, join as join_path
from optparse import OptionParser

from genshi.template import MarkupTemplate

# ------------------------------------------------------------------------------
# our main funktion
# ------------------------------------------------------------------------------

def main(argv=None):

    argv = argv or sys.argv[1:]
    op = OptionParser(usage="Usage: %prog [options]")

    op.add_option('-i', '--input', dest='input_file', default='',
                  help="the path to the genshi template")

    op.add_option('-o', '--output', dest='output_file', default='',
                  help="the filename of the production output file")

    op.add_option('-d', '--debug', dest='debug_file', default='',
                  help="the filename of the debug output file")

    options, args = op.parse_args(argv)

    if not (options.input_file and options.output_file):
        op.print_help()
        return

    input_file = open(options.input_file, 'rb')
    content = input_file.read()
    input_file.close()

    template = MarkupTemplate(content, encoding='utf-8')

    output_file = open(options.output_file, 'wb')
    output = template.generate().render('xhtml', encoding='utf-8')
    output_file.write(output)

    if options.debug_file:
        debug_file = open(options.debug_file, 'wb')
        output = template.generate(DEBUG=True).render('xhtml', encoding='utf-8')
        debug_file.write(output)

# ------------------------------------------------------------------------------
# self runner
# ------------------------------------------------------------------------------

if __name__ == '__main__':
    main()
