#! /usr/bin/env python

# No Copyright (-) 2010 The Ampify Authors. This file is under the
# Public Domain license that can be found in the root LICENSE file.

"""Airbeam provides the support structure for Tentapp."""

import sys

from optparse import OptionParser
from os import chdir, close, environ, getcwd, remove, urandom, write
from os.path import dirname, isdir, isfile, join, realpath

from simplejson import loads as decode_json
from tornado.ioloop import IOLoop

# ------------------------------------------------------------------------------
# Some Constants
# ------------------------------------------------------------------------------

Loop = IOLoop.instance()

# ------------------------------------------------------------------------------
# Main Runner
# ------------------------------------------------------------------------------

# Define the various options for the command line options parser.
op = OptionParser(usage="Usage: %prog", version="%prog 0.1")

op.add_option('--dev', action='store_true', help="enable dev mode")
op.add_option(
    '--host', help="specify the host [default: localhost]", default='localhost'
    )

op.add_option(
    '--port', type='int', default=9081, help="specify the port [default: 9081]"
    )

op.add_option(
    '--keyspace', dest='nodes',
    default='localhost:7080', help="specify the keyspace nodes"
    )

op.add_option(
    '--extension', default='', dest='path',
    help="specify the path to a custom extension module"
    )

# Parse the command line arguments and exit if no config file was specified.
options, _ = op.parse_args(sys.argv[1:])

host = options.host
port = options.port

# Load the custom extension module if one is present.
extension = options.path

if extension:
    execfile(extension, globals())

print "Running airbeam on %s:%s" % (host, port)
