#! /bin/sh

# No Copyright (-) 2010 The Ampify Authors. This file is under the
# Public Domain license that can be found in the root LICENSE file.

AMPIFY_ROOT=$(dirname $(dirname $BASH_SOURCE))

if [ "x$AMPIFY_ROOT" == "x" ]; then
	echo "ERROR: Sorry, couldn't detect the Ampify Root Directory."
fi

source $AMPIFY_ROOT/environ/ampenv.sh

python -m ampify.main $@
