#! /bin/bash

# Public Domain (-) 2010-2012 The Ampify Authors.
# See the Ampify UNLICENSE file for details.

# ==========================
# Ampify Environment Support
# ==========================
#
# NOTE: This script has only been tested in the context of a modern Bash Shell
# on Ubuntu Linux and OS X. Any patches to make it work under alternative Unix
# shells, versions and platforms are very welcome!
if [[ "x$BASH_SOURCE" == "x" ]]; then
	echo "Sorry, this only works under Bash shells atm. Patches welcome... =)"
	exit
fi

_OS_NAME=$(uname -s | tr 'A-Z' 'a-z')

# ------------------------------------------------------------------------------
# Self Execution
# ------------------------------------------------------------------------------

if [ "x$0" == "x$BASH_SOURCE" ]; then
	LSOF=$(lsof -p $$ 2> /dev/null | grep -E "/"$(basename $0)"$")
	case $_OS_NAME in
		darwin)
			__FILE=$(echo $LSOF | sed -E s/'^([^\/]+)\/'/'\/'/1 2>/dev/null);;
		linux)
			__FILE=$(echo $LSOF | sed -r s/'^([^\/]+)\/'/'\/'/1 2>/dev/null);;
		freebsd)
			__FILE=$(echo $LSOF | sed -E s/'^([^\/]+)\/'/'\/'/1 2>/dev/null);;
		*)
			echo "ERROR: The $_OS_NAME operating system is not yet supported.";
			exit
	esac
	if [ "x$#" != "x0" ]; then
		source $__FILE
		exec $@
	fi
	echo "Usage: ampenv runs differently depending on how it's invoked."
	echo
	echo "ampenv <command> [<param1> <param2> ...]"
	echo
	echo "    Execute shell commands with the Ampify environment set."
	echo "    For example, to run 'redpill build', just do:"
	echo
	echo "        $ ampenv redpill build"
	echo
	echo "source $__FILE"
	echo
	echo "    Extend your shell with the Ampify environment. You may"
	echo "    even want to add the above line to your .bashrc file."
	echo
	exit
fi

# ------------------------------------------------------------------------------
# Bash Version Detection
# ------------------------------------------------------------------------------

# Work out if we are running within an appropriate version of bash, i.e. v3.0+.
_BASH_VERSION=${BASH_VERSION%.*} # $BASH_VERSION normally looks something like:
                                 # 3.2b.17(1)-release

_BASH_MAJOR_VERSION=${_BASH_VERSION%.*}
_BASH_MINOR_VERSION=${_BASH_VERSION#*.}

if [ $_BASH_MAJOR_VERSION -le 2 ]; then
	echo "ERROR: You need to be running Bash 3.0+"
	return 1
fi

# ------------------------------------------------------------------------------
# Startup Env Detection
# ------------------------------------------------------------------------------

# Try to determine the absolute path of the enclosing root directory.
cd "$(dirname $BASH_SOURCE)" || return $?

_ENVIRON_DIRECTORY=`pwd -P 2> /dev/null` || return $?

cd $OLDPWD || return $?

export AMPIFY_ROOT=$(dirname $_ENVIRON_DIRECTORY)

# Exit if ``$AMPIFY_ROOT`` is not set.
if [ "x$AMPIFY_ROOT" == "x" ]; then
	echo "ERROR: Sorry, couldn't detect the Ampify Root Directory."
	return
fi

# ------------------------------------------------------------------------------
# Utility Functions
# ------------------------------------------------------------------------------

function _have () {
	unset -v _have
	type $1 &> /dev/null && _have="yes"
}

# ------------------------------------------------------------------------------
# Core Variables
# ------------------------------------------------------------------------------

export AMPIFY_LOCAL=$AMPIFY_ROOT/environ/local

_ENV_VAL=$AMPIFY_ROOT/environ:$AMPIFY_LOCAL/bin

if [ "x$PRE_AMPENV_PATH" != "x" ]; then
	export PATH=$_ENV_VAL:$PRE_AMPENV_PATH
else
	if [ "x$PATH" != "x" ]; then
		export PRE_AMPENV_PATH=$PATH
		export PATH=$_ENV_VAL:$PATH
	else
		export PATH=$_ENV_VAL
	fi
fi

case $_OS_NAME in
	darwin)
		if [ "x$PRE_AMPENV_DYLD_FALLBACK_LIBRARY_PATH" != "x" ]; then
			export DYLD_FALLBACK_LIBRARY_PATH=$AMPIFY_LOCAL/lib:$PRE_AMPENV_DYLD_FALLBACK_LIBRARY_PATH:/usr/local/lib:/usr/lib
		else
			if [ "x$DYLD_FALLBACK_LIBRARY_PATH" != "x" ]; then
				export PRE_AMPENV_DYLD_FALLBACK_LIBRARY_PATH=$DYLD_FALLBACK_LIBRARY_PATH
				export DYLD_FALLBACK_LIBRARY_PATH=$AMPIFY_LOCAL/lib:$DYLD_FALLBACK_LIBRARY_PATH:/usr/local/lib:/usr/lib
			else
				export DYLD_FALLBACK_LIBRARY_PATH=$AMPIFY_LOCAL/lib:/usr/local/lib:/usr/lib
			fi
		fi
		export DYLD_LIBRARY_PATH=/this/path/should/not/exist;;
	linux)
		if [ "x$PRE_AMPENV_LD_LIBRARY_PATH" != "x" ]; then
			export LD_LIBRARY_PATH=$AMPIFY_LOCAL/lib:$PRE_AMPENV_LD_LIBRARY_PATH
		else
			if [ "x$LD_LIBRARY_PATH" != "x" ]; then
				export PRE_AMPENV_LD_LIBRARY_PATH=$LD_LIBRARY_PATH
				export LD_LIBRARY_PATH=$AMPIFY_LOCAL/lib:$LD_LIBRARY_PATH
			else
				export LD_LIBRARY_PATH=$AMPIFY_LOCAL/lib
			fi
		fi;;
	freebsd)
		if [ "x$PRE_AMPENV_LD_LIBRARY_PATH" != "x" ]; then
			export LD_LIBRARY_PATH=$AMPIFY_LOCAL/lib:$PRE_AMPENV_LD_LIBRARY_PATH
		else
			if [ "x$LD_LIBRARY_PATH" != "x" ]; then
				export PRE_AMPENV_LD_LIBRARY_PATH=$LD_LIBRARY_PATH
				export LD_LIBRARY_PATH=$AMPIFY_LOCAL/lib:$LD_LIBRARY_PATH
			else
				export LD_LIBRARY_PATH=$AMPIFY_LOCAL/lib
			fi
		fi;;
	*) echo "ERROR: The $_OS_NAME operating system is not yet supported."
esac

if [ "x$PRE_AMPENV_MANPATH" != "x" ]; then
	export MANPATH=$AMPIFY_ROOT/doc/man:$AMPIFY_LOCAL/share/man:$PRE_AMPENV_MANPATH
else
	if [ "x$MANPATH" != "x" ]; then
		export PRE_AMPENV_MANPATH=$MANPATH
		export MANPATH=$AMPIFY_ROOT/doc/man:$AMPIFY_LOCAL/share/man:$MANPATH
	else
		export MANPATH=$AMPIFY_ROOT/doc/man:$AMPIFY_LOCAL/share/man:
	fi
fi

# ------------------------------------------------------------------------------
# CA Cert Location Specifier
# ------------------------------------------------------------------------------

export CACERT=$AMPIFY_LOCAL/share/cacerts/ca.cert

# ------------------------------------------------------------------------------
# Go Related Variables
# ------------------------------------------------------------------------------

export GOBIN=$AMPIFY_LOCAL/bin

# ------------------------------------------------------------------------------
# Redpill Related Variables
# ------------------------------------------------------------------------------

export REDPILL_ENVIRON=$_ENVIRON_DIRECTORY

# ------------------------------------------------------------------------------
# Rust Related Variables
# ------------------------------------------------------------------------------

export RUSTBIN=$AMPIFY_LOCAL/bin
export RUSTBUILD=$AMPIFY_ROOT/build
export RUSTPATH=$AMPIFY_ROOT/src

# ------------------------------------------------------------------------------
# Auto-completing Function
# ------------------------------------------------------------------------------

# This function sets the special ``OPTPARSE_AUTO_COMPLETE`` environment variable
# which can be used by commands to figure out whether they should auto-complete.
_optparse_completion() {
	COMPREPLY=( $( \
	COMP_LINE=$COMP_LINE  COMP_POINT=$COMP_POINT \
	COMP_WORDS="${COMP_WORDS[*]}"  COMP_CWORD=$COMP_CWORD \
	OPTPARSE_AUTO_COMPLETE=1 $1 ) )
}

# ------------------------------------------------------------------------------
# Setup Bash Completion
# ------------------------------------------------------------------------------

# First, try and figure out if we are inside an interactive shell.
if test "$PS1"; then

	# Then, turn on the extended globbing and programmable completion.
	shopt -s extglob progcomp

	# Register the completers.
	complete -o default -F _optparse_completion amp
	complete -o default -F _optparse_completion ampnode
	complete -o default -F _optparse_completion ampstore
	complete -o default -F _optparse_completion assetgen
	complete -o default -F _optparse_completion blobnode
	complete -o default -F _optparse_completion bloqi
	complete -o default -F _optparse_completion bolt
	complete -o default -F _optparse_completion git-review
	complete -o default -F _optparse_completion git-slave
	complete -o default -F _optparse_completion live-server
	complete -o default -F _optparse_completion live-store
	complete -o default -F _optparse_completion naaga
	complete -o default -F _optparse_completion redpill
	complete -o default -F _optparse_completion review-server
	complete -o default -F _optparse_completion rusty
	complete -o default -F _optparse_completion wifistat

fi

# ------------------------------------------------------------------------------
# Clean Up
# ------------------------------------------------------------------------------

unset _BASH_MAJOR_VERSION _BASH_MINOR_VERSION _BASH_VERSION
unset _ENV_VAL _ENVIRON_DIRECTORY _have _OS_NAME
