#! /usr/bin/env python

# Public Domain (-) 2010-2011 The Ampify Authors.
# See the UNLICENSE file for details.

"""Build recipes for Ampify."""

if NUMBER_OF_CPUS > 1:
    PARALLEL = '-j%i' % NUMBER_OF_CPUS
else:
    PARALLEL = ''

# ------------------------------------------------------------------------------
# berkeleydb
# ------------------------------------------------------------------------------

RECIPES['berkeleydb'] = [{
    'version': '4.8.30',
    'hash': 'aad516a6e991e1e48dd45ba410f0b74c465bc54fb2ad04e00df60594f30a256c',
    'before': lambda: chdir('build_unix'),
    'config_command': '../dist/configure',
    'config_flags': ['--enable-cxx', '--prefix', LOCAL],
    }]

# ------------------------------------------------------------------------------
# bsdiff
# ------------------------------------------------------------------------------

def install_bsdiff():
    copy('bsdiff', join(BIN, 'bsdiff'))
    copy('bspatch', join(BIN, 'bspatch'))

RECIPES['bsdiff'] = [{
    'requires': ['bzip2'],
    'version': '4.3',
    'hash': '6f43c5246cdb60e58134144b72328918eb4a23c2a28880914f3431a76fbf657b',
    'after': install_bsdiff,
    'commands': [
        [MAKE],
        ]
    }]

# ------------------------------------------------------------------------------
# bzip2
# ------------------------------------------------------------------------------

if PLATFORM == 'darwin':
    BZIP2_MAKEFILE = 'Makefile-libbz2_dylib'
else:
    BZIP2_MAKEFILE = 'Makefile-libbz2_so'

RECIPES['bzip2'] = [{
    'version': '1.0.5',
    'hash': 'edda8d2c38106dfd88a2fc4610d2aa85d869effc0a30f206c78100bf99703585',
    'commands': [
        [MAKE, 'install', 'PREFIX=%s' % LOCAL],
        [MAKE, 'clean'],
        [MAKE, '-f', BZIP2_MAKEFILE, 'all', 'PREFIX=%s' % LOCAL]
        ]
    }]

# ------------------------------------------------------------------------------
# closure
# ------------------------------------------------------------------------------

RECIPES['closure'] = [{
    'version': '2010-03-24',
    'hash': '43281e5b891fac5156dedd47773982cfd931a2233e3b586b966ca1a701e5783e',
    'type': 'jar'
    }]

# ------------------------------------------------------------------------------
# go
# ------------------------------------------------------------------------------

RECIPES['go'] = [{
    'type': 'submodule',
    'path': 'third_party/go',
    'before': lambda: chdir('src'),
    'commands': [
        ['./all.bash']
        ]
    }]

# ------------------------------------------------------------------------------
# keyspace
# ------------------------------------------------------------------------------

def copy_keyspace_py_lib():
    directory = join(getcwd(), 'bin', 'python')
    pylibs = join(ROOT, 'third_party', 'pylibs')
    mkdir(pylibs)
    for file in listdir(directory):
        if file.endswith('.so') or file.endswith('.py'):
            copy(join(directory, file), join(pylibs, file))

RECIPES['keyspace'] = [{
    'version': '1.8.0',
    'hash': '5f6425411eff961e1bf9122aa3f59a898cee4af0fcd7a1abe29b84a3cf6539e2',
    'after': copy_keyspace_py_lib,
    'env': {
        'PREFIX': LOCAL
        },
    'commands': [
        [MAKE],
        [MAKE, 'install'],
        [MAKE, 'pythonlib']
        ]
    }]

# ------------------------------------------------------------------------------
# libevent
# ------------------------------------------------------------------------------

RECIPES['libevent'] = [{
    'version': '1.4.13',
    'hash': ''
    }]

# ------------------------------------------------------------------------------
# libnatpmp
# ------------------------------------------------------------------------------

RECIPES['libnatpmp'] = [{
    'requires': ['python'],
    'version': '20100202',
    'hash': '8236d11bb83f13fdc5967a78fa7f5e43a429ab2e59b01e2c4991627e621162e2',
    'commands': [
        [MAKE],
        [sys.executable, 'setup.py', 'build_ext', '-i']
        ],
    'after': lambda: copy('libnatpmp.so', join(ROOT, 'third_party', 'pylibs'))
    }]

# ------------------------------------------------------------------------------
# makeucd
# ------------------------------------------------------------------------------

MAKEUCD_SCRIPT = join(ENVIRON, 'makeucd')
UCD_DATA_FILE = join(SHARE, 'ucd', 'UnicodeData.txt')
UCD_JS_FILE = join(SRC, 'jsutil', 'ucd.js')

RECIPES['makeucd'] = [{
    'requires': ['python', 'ucd'],
    'type': 'makelike',
    'depends': [MAKEUCD_SCRIPT],
    'outputs': [UCD_JS_FILE],
    'generators': [
        [MAKEUCD_SCRIPT, UCD_DATA_FILE, UCD_JS_FILE]
        ]
    }]

# ------------------------------------------------------------------------------
# miniupnpc
# ------------------------------------------------------------------------------

RECIPES['miniupnpc'] = [{
    'requires': ['python'],
    'version': '1.4.20100609',
    'hash': 'dfc902939514a752235890572211a8dfa5e4b97b31d47e5952281fca7c4767f7',
    'commands': [
        [MAKE],
        [sys.executable, 'setup.py', 'build_ext', '-i']
        ],
    'after': lambda: copy('miniupnpc.so', join(ROOT, 'third_party', 'pylibs'))
    }]

# ------------------------------------------------------------------------------
# nodejs
# ------------------------------------------------------------------------------

RECIPES['node'] = [{
    'version': '0.2.0',
    'hash': '0116ff380a63271e684e05a80207cb8e01b40797d831b6c8c92a3658b860efb5'
    }]

# ------------------------------------------------------------------------------
# nginx
# ------------------------------------------------------------------------------

NGINX = join(LOCAL, 'share', 'nginx')
NGINX_TMP = join(NGINX, 'tmp')

RECIPES['nginx'] = [{
    'requires': ['openssl', 'pcre', 'zlib'],
    'version': '0.7.67',
    'hash': '7dba22b0e17a996af4ec409084f38d33a3cbc5c678abb980470dc932c9200e8f',
    'before': lambda: mkdir(NGINX_TMP),
    'config_flags': [
        '--with-http_stub_status_module',
        '--prefix=%s' % NGINX,
        '--sbin-path=%s' % join(BIN, 'nginx'),
        '--conf-path=%s' % join(NGINX, 'etc', 'nginx.conf'),
        '--pid-path=%s' % join(NGINX, 'var', 'nginx.pid'),
        '--error-log-path=%s' % join(NGINX, 'var', 'error.log'),
        '--http-log-path=%s' % join(NGINX, 'var', 'access.log'),
        '--http-client-body-temp-path=%s' % join(NGINX_TMP, 'http_client'),
        '--http-proxy-temp-path=%s' % join(NGINX_TMP, 'proxy'),
        '--http-fastcgi-temp-path=%s' % join(NGINX_TMP, 'fastcgi'),
        '--with-cc-opt=-I%s' % INCLUDE, '--with-ld-opt=-L%s' % LIB,
        '--with-ipv6', '--with-http_ssl_module'
        ]
    }]

# ------------------------------------------------------------------------------
# openssl
# ------------------------------------------------------------------------------

RECIPES['openssl'] = [{
    'requires': ['zlib'],
    'version': '0.9.8o',
    'hash': '7c8639905b7122f07378d6079eeeebd7ff0a27f126aba6fd00a8ac98a583f263',
    'commands': [
        ['./config', 'shared', 'no-idea', 'no-krb5', 'no-mdc2', 'zlib',
         '--prefix=%s' % LOCAL, '--openssldir=%s' % join(SHARE, 'ssl'),
         '-L%s' % LIB, '-I%s' % INCLUDE],
        [MAKE, 'depend'],
        [MAKE],
        [MAKE, 'install']
        ]
    }]

# ------------------------------------------------------------------------------
# pcre
# ------------------------------------------------------------------------------

RECIPES['pcre'] = [{
    'requires': ['zlib'],
    'version': '8.10',
    'hash': 'c82ac809d5bd0a281400ec4b4368ce1d9f93b589c42bd9b413f8dfc187c9541d'
    }]

# ------------------------------------------------------------------------------
# pyutil
# ------------------------------------------------------------------------------

PYUTIL_PYX_FILES = glob(join(SRC, 'pyutil', '*.pyx'))
if PLATFORM != 'darwin':
    PYUTIL_PYX_FILES.remove(join(SRC, 'pyutil', 'darwinsandbox.pyx'))

PYUTIL_SO_FILES = [
    file.rsplit('.pyx', 1)[0] + '.so' for file in PYUTIL_PYX_FILES
    ]

RECIPES['pyutil'] = [{
    'requires': ['python'],
    'type': 'makelike',
    'before': lambda: chdir(SRC),
    'depends': PYUTIL_PYX_FILES + [join(ROOT, 'src', 'setup.py')],
    'outputs': PYUTIL_SO_FILES,
    'after': lambda: rmdir('build'),
    'generators': [
        lambda: [remove(path) for path in PYUTIL_SO_FILES if isfile(path)],
        [sys.executable, 'setup.py', 'build_ext', '-i']
        ]
    }]

# ------------------------------------------------------------------------------
# pylibs
# ------------------------------------------------------------------------------

RECIPES['pylibs'] = [{
    'type': 'submodule',
    'requires': ['python'],
    'path': 'third_party/pylibs',
    'after': lambda: rmdir('build'),
    'commands': [
        [sys.executable, 'setup.py', 'build_ext', '-i']
        ]
    }]

# ------------------------------------------------------------------------------
# python
# ------------------------------------------------------------------------------

RECIPES['python'] = [{
    'requires': ['bzip2', 'openssl', 'readline', 'zlib'],
    'version': '2.7',
    'hash': 'f559ac6bf5a112c63659c631f3ad27f41ecc3d8c64ea5873da1bfa50b738f125',
    'after': lambda: rmdir(join(LOCAL, 'lib', 'python2.7', 'test')),
    'config_flags': [
        '--enable-unicode=ucs2', '--enable-ipv6', '--prefix=%s' % LOCAL
        ],
    'env': {
        'CPPFLAGS': CPPFLAGS,
        'LDFLAGS': LDFLAGS
        }
    }]

# ------------------------------------------------------------------------------
# readline
# ------------------------------------------------------------------------------

RECIPES['readline'] = [{
    'version': '6.1',
    'hash': '336f955389fb3a91915e845d8e0919e5191af61c52d827d0e95e728a44a16ec4',
    'config_flags': [
        '--infodir=%s' % join(LOCAL, 'share', 'info'), '--prefix=%s' % LOCAL
        ]
    }]

# ------------------------------------------------------------------------------
# redis
# ------------------------------------------------------------------------------

RECIPES['redis'] = [{
    'type': 'submodule',
    'path': 'third_party/redis',
    'after': lambda: copy(
        join(getcwd(), 'src', 'redis-server'), join(BIN, 'redis')
        ),
    'commands': [
        [MAKE]
        ]
    }]

# ------------------------------------------------------------------------------
# ucd
# ------------------------------------------------------------------------------

RECIPES['ucd'] = [{
    'required': ['python'],
    'version': '5.2.0',
    'hash': '12363cd8793148283551a69478ec42220c9e43c91d4dd77557df5d5265199e51',
    'type': 'resource'
    }]

# ------------------------------------------------------------------------------
# yuicompressor
# ------------------------------------------------------------------------------

RECIPES['yuicompressor'] = [{
    'version': '2.4.2',
    'hash': '1289ef00c770d9559a826542ff30a2197891915ef973ea9c7cdc0be613f6a108',
    'type': 'jar'
    }]

# ------------------------------------------------------------------------------
# zlib
# ------------------------------------------------------------------------------

RECIPES['zlib'] = [{
    'version': '1.2.5',
    'hash': 'cbd4d0d617e901470cbe60bc483fdb95122de8baf8b08d96e3c8928ae483f1ca',
    'config_flags': ['--shared'],
    'make_flags': ['install', 'prefix=%s' % LOCAL]
    }]
