#! /usr/bin/env python

# No Copyright (-) 2010 The Ampify Authors. This file is under the
# Public Domain license that can be found in the root LICENSE file.

"""A git-command that emulates GitHub's language graph info."""

# usage variants:
#
#     git languages
#     git languages all
#     git languages py

import pylibs
import sys

from decimal import Decimal, ROUND_HALF_UP
from os.path import splitext
from os import lstat
from stat import ST_SIZE, S_ISLNK
from pyutil.env import run_command

files = {}

for file in run_command(['git', 'ls-files']).strip().splitlines():
    base, ext = splitext(file)
    ext = ext[1:]
    if base and ext:
        if ext not in files:
            files[ext] = {}
        info = lstat(file)
        if not S_ISLNK(info.st_mode):
            files[ext][file] = info[ST_SIZE]

if sys.argv[-1] == 'all':
    sys.argv.pop()
else:
    valid_exts = [
        'awk', 'c', 'coffee', 'cpp', 'el', 'go', 'h', 'java', 'js',
        'rb', 'pl', 'py', 'sh', 'tcl', 'vim'
        ]
    for ext in files.keys():
        if ext not in valid_exts:
            del files[ext]

def merge(ext1, ext2, d):
    if ext1 not in d:
        return
    if ext2 not in d:
        d[ext2] = {}
    d[ext2].update(d[ext1])
    del d[ext1]

merge('h', 'c', files)
merge('awk', 'sh', files)

if not sys.argv[1:]:
    meta = 0
    totals = {}
    for ext in files:
        total = sum(files[ext].values())
        if total:
            totals[ext] = total
            meta += total
    for ext in sorted(totals, key=lambda x: totals[x]):
        weight_f = float(totals[ext] * 100) / meta
        weight = Decimal(totals[ext] * 100) / Decimal(meta)
        weight = weight.quantize(Decimal('10'), ROUND_HALF_UP)
        print "%8s    %-9s %.2f\t%d" % (ext, totals[ext], weight_f, weight)
    sys.exit()

ext = sys.argv[1]
if ext not in files:
    sys.exit()

total = 0
files = files[ext]

for file in sorted(files, key=lambda x: files[x]):
    print "%s\t%s" % (files[file], file)
    total += files[file]

print "\t------------------"
print "%s\ttotal" % total
