#! /usr/bin/env bash

# Public Domain (-) 2010-2012 The Ampify Authors.
# See the Ampify UNLICENSE file for details.

if [[ "x$BASH_SOURCE" == "x" ]]; then
	echo "Sorry, this only works under Bash shells atm. Patches welcome... =)"
	exit
fi

AMPIFY_ROOT=$(dirname $(dirname $0))

if [[ "x$AMPIFY_ROOT" == "x" ]]; then
	echo "ERROR: Sorry, couldn't detect the Ampify Root Directory."
fi

. $AMPIFY_ROOT/environ/ampenv.sh

# Exit if the Python version is not a 2.x more recent than 2.7.
python -c "import sys
if (not hasattr(sys, 'version_info')) or sys.version_info < (2, 7):
    print('ERROR: Sorry, you do not have a compatible Python version.')
    print('ERROR: It needs to be a 2.x version more recent than 2.7.')
    sys.exit(1)

if sys.version_info >= (3,):
    print('ERROR: Sorry, you do not have a compatible Python version.')
    print('ERROR: Python 3 is not supported. You need Python 2.7+ version.')
    sys.exit(1)"

version_check_status=$?
if [ $version_check_status -ne 0 ]; then
	exit $version_check_status
fi

PYTHONPATH=$AMPIFY_ROOT/environ:$PYTHONPATH python -m redpill $@
