#! /usr/bin/env python

# Public Domain (-) 2010-2011 The Ampify Authors.
# See the Ampify UNLICENSE file for details.

"""
==============
Redpill Daemon
==============

The redpill takes care of updating a deployed Ampify setup.

* Build -- max(N/200, 2) -- if more than 2 matching uname -mrs / rev id / ampify_root
* Create tarball
* Compare hash
* Generate diff to desired versions
* Compare hash
* Distribute bsdiffs

~/.ampify

* Send current revision IDs
* Receive bsdiff
* Apply bsdiffs
* Untar
* Tell nginx to go into system upgrade mode
* Send KILL signal to amp processes
* Move ampify/instance directories
* Move untarred directories to become the new ampify/instance directories
* Start amp processes
* Tell nginx to go into normal mode
* Move .git directory
* Delete the previous directories

* Reload redpill

"""

