#! /usr/bin/env ruby

# No Copyright (-) 2010 The Ampify Authors. This file is under the
# Public Domain license that can be found in the root LICENSE file.

require File.join(File.dirname(__FILE__), 'rubylibs')
require 'haml/exec'
require 'haml/util'

if ARGV.length == 0
    ARGV << "--help"
elsif not ARGV.include? "--cache-location"
    ARGV.unshift "--cache-location", MAIN_ROOT.join('.sass-cache').to_s
end

#Haml.init_rails(binding) if defined?(Haml)
opts = Haml::Exec::Sass.new(ARGV)
opts.parse!
