#! /usr/bin/env ruby

# Public Domain (-) 2010-2011 The Ampify Authors.
# See the UNLICENSE file for details.

require 'pathname'

MAIN_ROOT = Pathname.new(__FILE__).realpath.dirname.dirname
$:.unshift MAIN_ROOT.join('third_party', 'haml', 'lib')

require 'haml/exec'
require 'haml/util'

if ARGV.length == 0
    ARGV << "--help"
elsif not ARGV.include? "--cache-location"
    ARGV.unshift "--cache-location", MAIN_ROOT.join('.sass-cache').to_s
end

opts = Haml::Exec::Sass.new(ARGV)
opts.parse!
