#! /usr/bin/env python

# No Copyright (-) 2010 The Ampify Authors. This file is under the
# Public Domain license that can be found in the root LICENSE file.

import sys

from os.path import expanduser, exists

# ------------------------------------------------------------------------------
# some konstants
# ------------------------------------------------------------------------------

CONFIG_FILE = expanduser("~/.slavebuildconfig")

if not exists(CONFIG_FILE):
    print("Couldn't find the slave build config file: %s" % CONFIG_FILE)
    sys.exit(1)
