#! /usr/bin/env python

# No Copyright (-) 2010 The Ampify Authors. This file is under the
# Public Domain license that can be found in the root LICENSE file.

import sys

from os import getcwd
from os.path import dirname, join as join_path, realpath

version = "1.5.16"

wafadmin_directory = join_path(
    dirname(dirname(realpath(__file__))),
    'third_party', 'pylibs', 'wafadmin'
    )

tools_directory = join_path(wafadmin_directory, 'Tools')

sys.path.insert(0, join_path(wafadmin_directory, '3rdparty'))
sys.path.insert(0, tools_directory)
sys.path.insert(0, wafadmin_directory)

import Scripting

Scripting.prepare(tools_directory, getcwd(), version, wafadmin_directory)
