#! /usr/bin/env python

# No Copyright (-) 2004-2010 The Ampify Authors. This file is under the
# Public Domain license that can be found in the root LICENSE file.

"""Yatiblog -- Blog/Documentation Generator."""

import pylibs

from pyutil.yatiblog import main

main()
