#! /usr/bin/env python

# Public Domain (-) 2004-2011 The Ampify Authors.
# See the Ampify UNLICENSE file for details.

"""Yatiblog -- Blog/Documentation Generator."""

import pylibs

from yatiblog.main import main

main()
