#! /usr/bin/env python

# Released into the Public Domain by tav <tav@espians.com>

import sys

from os.path import expanduser, exists

# ------------------------------------------------------------------------------
# some konstants
# ------------------------------------------------------------------------------

CONFIG_FILE = expanduser("~/.ampbuildconfig")

if not exists(CONFIG_FILE):
    print("Couldn't find the build slave config file: %s" % CONFIG_FILE)
    sys.exit(1)
