#! /usr/bin/env ruby

# No Copyright (-) 2008-2010 The Ampify Authors. This file is under the
# Public Domain license that can be found in the root LICENSE file.

require File.join(File.dirname(__FILE__), 'rubylibs')

require 'haml/exec'

if ARGV.length == 0
    puts "Usage: sass <file>"
    Process.exit
end

opts = Haml::Exec::Sass.new(ARGV)
opts.parse!
