# Public Domain (-) 2010-2011 The Ampify Authors.
# See the UNLICENSE file for details.

include $(GOROOT)/src/Make.inc

TARG=amp/optparse
GOFILES=\
        optparse.go\

include $(GOROOT)/src/Make.pkg
