# Public Domain (-) 2010-2011 The Ampify Authors.
# See the Ampify UNLICENSE file for details.

include $(GOROOT)/src/Make.inc

TARG=amp/log
GOFILES=\
		console.go\
		file.go\
		log.go\
		network.go\

include $(GOROOT)/src/Make.pkg
