# No Copyright (-) 2010 The Ampify Authors. This file is under the
# Public Domain license that can be found in the root LICENSE file.

include $(GOROOT)/src/Make.inc

TARG=ampzero
GOFILES=\
	ampzero.go\

include $(GOROOT)/src/Make.cmd
