# No Copyright (-) 2010 The Ampify Authors. This file is under the
# Public Domain license that can be found in the root LICENSE file.

include $(GOROOT)/src/Make.inc

TARG=amp/pyksproxy
GOFILES=\
        pyksproxy.go\

include $(GOROOT)/src/Make.pkg
