#! /usr/bin/env python

# Public Domain (-) 2015 The Ampify Authors.
# See the Ampify UNLICENSE file for details.

"""Checksum Verifier."""

import sys

from hashlib import sha512

filename, digest = sys.argv[1:]
hasher = sha512()

with open(filename, 'rb') as f:
    while 1:
        block = f.read(65536)
        if not block:
            break
        hasher.update(block)

if digest != hasher.hexdigest():
    sys.stderr.write("!! ERROR: Invalid checksum for downloaded file: %s !!\n" % filename)
    sys.exit(1)
