# Public Domain (-) 2010-2011 The Ampify Authors.
# See the UNLICENSE file for details.

include $(GOROOT)/src/Make.inc

TARG=amp/logging
GOFILES=\
        logging.go\

include $(GOROOT)/src/Make.pkg
