# Public Domain (-) 2011 The Ampify Authors.
# See the Ampify UNLICENSE file for details.

include $(GOROOT)/src/Make.inc

TARG=amp/argo/json
GOFILES=\
	decode.go\
	encode.go\
	$(GOROOT_ORIGINAL)/src/pkg/json/indent.go\
	$(GOROOT_ORIGINAL)/src/pkg/json/scanner.go\
	$(GOROOT_ORIGINAL)/src/pkg/json/stream.go\
	$(GOROOT_ORIGINAL)/src/pkg/json/tags.go\

include $(GOROOT)/src/Make.pkg
