# Public Domain (-) 2010-2011 The Ampify Authors.
# See the Ampify UNLICENSE file for details.

include $(GOROOT)/src/Make.inc

TARG=amp/crypto
GOFILES=\
        crypto.go\

include $(GOROOT)/src/Make.pkg
