# Public Domain (-) 2011 The Ampify Authors.
# See the Ampify UNLICENSE file for details.

include $(GOROOT)/src/Make.inc

TARG=amp/structure
GOFILES=\
		dict.go\
        prefixtree.go\

include $(GOROOT)/src/Make.pkg
